# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('headline', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(default='Personal Development', max_length=140)),
                ('image_url', models.TextField(null=True)),
                ('lectures', models.CharField(max_length=4, null=True)),
                ('duration', models.CharField(max_length=3, null=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Chinese', 'Chinese'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Russian', 'Russian'), ('Portuguese', 'Portuguese'), ('Japanese', 'Japanese')], default='English', max_length=10)),
                ('rating', models.CharField(max_length=3, null=True)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=12)),
                ('price', models.CharField(choices=[('$ FREE', '$ FREE'), ('29$', '29$'), ('59$', '59$'), ('79$', '79$'), ('99$', '99$')], default='$ FREE', max_length=10)),
                ('url', models.TextField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('instructor', models.CharField(max_length=100, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
